name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Copy .env file
      run: cp .env.example .env

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
        tools: pecl
        extensions: mbstring, intl, json, phalcon4
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
